apiVersion: v1
kind: Pod
metadata:
   name: rand-nu-gen
spec:
  containers:
      - image: alpine
        name: alpine
        command: ["/bin/sh", "-c"]
        args: ["shuf -i 0-100 -n 1 >> /opt/nuber.out;"]
        volumeMounts:
           - mountPath: /opt
             name: data-vol
  volumes:
      - name: data-vol
        hostPath:
           path: /data
           type: Directory
