apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-10-19T13:03:38Z
  labels:
    tier: db
  name: redis
  namespace: default
  resourceVersion: "2441"
  selfLink: /api/v1/namespaces/default/pods/redis
  uid: de02f69b-f270-11e9-9c39-0242ac110014
spec:
  containers:
  - image: redis:alpine
    imagePullPolicy: IfNotPresent
    name: redis
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-5z5kc
      readOnly: true
  dnsPolicy: ClusterFirst
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-5z5kc
    secret:
      defaultMode: 420
      secretName: default-token-5z5kc
status:
  phase: Pending
  qosClass: BestEffort
