apiVersion: v1
kind: Service
metadata:
  name: culst-ip-service
  labels:
    app: myapp
    type: frontend

spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - targetPort: 80
      port: 80
