apiVersion: v1
kind: Service
metadata:
  name: loadbal-service
  labels:
    app: myapp
    type: frontend

spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
