apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  labels:
    app: myapp
    type: frontend

spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
