apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  labels:
    app: myapp
spec:
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: daemonset-con
          image: k8s.gcr.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
     app: myapp 
